### ISSUE TITLE
iOS bugs

### ISSUE THREAD

**Issue by zanhk** [Elisha-Misoi/Nomadic#23]
- [ ] Missing `GoogleService-Info.plist ` (when calling `Firebase.Core.App.Configure();`)
- [x] Custom renderer for search bar ( I alread have a solution for this )

---

![2020-06-08_09-37-37-](https://user-images.githubusercontent.com/17980844/84073199-a2551c80-a9d0-11ea-8f2f-3b84198a7df1.png)
![2020-06-08_09-37-56-](https://user-images.githubusercontent.com/17980844/84073213-a7b26700-a9d0-11ea-9944-9e3086c00516.png)

---

- [ ] Top scrollbar is bugged

iPhone 11
![2020-06-08_09-37-05-](https://user-images.githubusercontent.com/17980844/84073287-c87abc80-a9d0-11ea-8b7f-414f957f122c.png)
iPad
![2020-06-08_09-36-12-](https://user-images.githubusercontent.com/17980844/84073293-cadd1680-a9d0-11ea-9974-32f66d348813.png)
iPhone 8
![2020-06-08_09-45-38-](https://user-images.githubusercontent.com/17980844/84073814-ca914b00-a9d1-11ea-8603-95f7fc462554.png)

- [ ] Start the padding from top to avoid center alignement on ipad

![2020-06-08_09-35-54-](https://user-images.githubusercontent.com/17980844/84073352-eea05c80-a9d0-11ea-8b22-47b01afdfa6f.png)

**Comment by ElishaMisoi** [comment]
Hello @zk-g, this app wasn't tested on iOS. If you'd like to, you can raise a PR on this. I'll appreciate the contribution.

**Comment by zanhk** [comment]
> Hello @zk-g, this app wasn't tested on iOS. If you'd like to, you can raise a PR on this. I'll appreciate the contribution.

> Missing GoogleService-Info.plist (when calling Firebase.Core.App.Configure();)

For this point I ll need that you download that file from your firebase console. It should not contain personal information but check before.

**Comment by ElishaMisoi** [comment]
> 
> 
> > Hello @zk-g, this app wasn't tested on iOS. If you'd like to, you can raise a PR on this. I'll appreciate the contribution.
> 
> > Missing GoogleService-Info.plist (when calling Firebase.Core.App.Configure();)
> 
> For this point I ll need that you download that file from your firebase console. It should not contain personal information but check before.

Hi @zk-g , There's a blog post about adding [Google Authentication](https://link.medium.com/UsQv6t9O15) which is also linked to using Firebase Firestore (by adding the GoogleServices-info.plist file). 

It can be detrimental on my side adding the file from my Firebase Project. Since the project is open to anyone, exposing the file might lead to undesired results. So I ignored the file in .gitignore.

But we have the blog post in place, I think the best thing to do is to comment that line in AppDelegate.cs.

If you'd like to proceed to Add Authentication and user account syncing, please follow the article on how to do it and add it from the Firebase Project.

Thanks for pointing out that an error is thrown due to the missing file. I will update README and include the issue and how to solve it.
